### ISSUE TITLE
ci: enable codecov on repo

### ISSUE THREAD

**Issue by andrewb1269** [hiero-ledger/hiero-cryptography#190]
Enable codecov on this repo as mentioned in audit story #20

**Comment by andrewb1269** [comment]
Some notes: 
This is the solo example:
https://github.com/hashgraph/solo/blob/main/codecov.yml
https://github.com/hashgraph/solo/blob/main/.github/workflows/zxc-code-analysis.yaml one workflow

Though [codecov.io](http://codecov.io/) will probably give you cleaner examples of both

**Comment by andrewb1269** [comment]
```
- name: Upload test results to Codecov
  if: ${{ !cancelled() }}
  uses: codecov/test-results-action@v1
  with:
    token: ${{ secrets.CODECOV_TOKEN }}
```
