### ISSUE TITLE
publish_release workflow fails github release job because of improper java setup variables assignment

### ISSUE THREAD

**Issue by PavelSBorisov** [hiero-ledger/hiero-cryptography#195]
### Description

The publish_release workflow's create-github-release job fails the java setup step because of issues with the java version and distribution variables sourcing:
```
      - name: Setup Java
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
```

### Steps to reproduce

Run the publish_release workflow.

### Additional context

Run logs:
```
Run actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa06[1](https://github.com/hashgraph/hedera-cryptography/actions/runs/12634777811/job/35203621291#step:7:1)b
  with:
    java-package: jdk
    check-latest: false
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true
    job-status: success
    token: ***
  env:
    REGISTRY: ghcr.io
    LC_ALL: C.UTF-[8](https://github.com/hashgraph/hedera-cryptography/actions/runs/12634777811/job/35203621291#step:7:8)
    GRADLE_CACHE_USERNAME: ***
    GRADLE_CACHE_PASSWORD: ***
Error: Input required and not supplied: distribution
```

### Version

N/A

### Operating system

None
